### ISSUE TITLE
CR .spec.container fields and using tagged container images

### ISSUE THREAD

**Issue by komish** [nuodb/nuodb-operator#37]
Thanks for the quick work here on the operator image versioning https://github.com/operator-framework/community-operators/pull/864!

Opening up this issue (discussion) here (as opposed to in that CSV PR) as it has more to do with the overall approach to the operand's versioning than the CSV itself. 

The CRs ([example](https://github.com/nuodb/nuodb-operator/blob/master/deploy/crds/nuodb_v2alpha1_nuodb_cr.yaml)) take in a container image as well and the example uses the `latest` tag. 

I'm looking to find out more the approach here with regards to upgrading the operand (NuoDB, Insights). At face value, I would think a pod recycle could potentially put the infrastructure into an inconsistent state (as in, different versions of the component itself) if it occurs after a new image has been cut and tagged with `latest`. 

Having the ability to override the container image seems fine, and I haven't gone through yet to see what happens by default (if I don't specify a container image), but I'm looking for some insights on how that risk of variability might be addressed the way things sit currently.

**Comment by Ashutosh-Shukla** [comment]
@komish Thanks for bringing that up, this would be solved in this PR 
[Tag correct images](https://github.com/nuodb/nuodb-operator/pull/35)

**Comment by komish** [comment]
@Ashutosh-Shukla understood, I'll keep watching that PR and will leave this open for the moment.
